name: suite-de-testes-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          newman run collections/fake-store-api-qa-automation.postman_collection.json \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: reports/report.html
